INSERT INTO customer(username, password) VALUES('admin', 'admin')
INSERT INTO customer(username, password) VALUES('guest', 'guest')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Apple', 'Apple description', 8.40, 'fruit', 'https://i.imgur.com/ckSB7el.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Tomato', 'Tomato description', 4.20, 'fruit', 'https://i.imgur.com/QcRrHUt.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Cabbage', 'Cabbage description', 2.10, 'greenery', 'https://i.imgur.com/QJyCPao.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Carrot', 'Carrot description', 6.30, 'vegetable', 'https://i.imgur.com/xub1HuS.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Watermelon', 'Watermelon description', 1.05, 'fruit', 'https://i.imgur.com/srNfjDd.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Pineapple', 'Pineapple description', 2.52, 'fruit', 'https://i.imgur.com/LTuoYom.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Purple Onion', 'Purple Onion description', 2.94, 'vegetable', 'https://i.imgur.com/3Dt29PD.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Onion', 'Onion description', 1.26, 'vegetable', 'https://i.imgur.com/YBPQwNL.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Yam', 'Yam description', 4.20, 'vegetable', 'https://i.imgur.com/Hfc4TPE.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Cassava', 'Cassava description', 5.25, 'vegetable', 'https://i.imgur.com/thzo7J3.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Potato', 'Potato description', 5.46, 'vegetable', 'https://i.imgur.com/F2eJ3UL.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Papaya', 'Papaya description', 2.10, 'fruit', 'https://i.imgur.com/7G8ZXkc.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Pumpkin', 'Pumpkin description', 6.72, 'vegetable', 'https://i.imgur.com/hwgcKXG.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Red Pepper', 'Red Pepper description', 3.78, 'vegetable', 'https://i.imgur.com/hGOwcTv.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Corn', 'Corn description', 3.36, 'vegetable', 'https://i.imgur.com/az1pS23.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Broccoli', 'Broccoli description', 8.40, 'greenery', 'https://i.imgur.com/tAGC5ra.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Grape', 'Grape description', 7.35, 'fruit', 'https://i.imgur.com/jKA7IBR.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Lettuce', 'Lettuce description', 6.30, 'vegetable', 'https://i.imgur.com/fLmkFQe.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Cucumber', 'Cucumber description', 4.20, 'vegetable', 'https://i.imgur.com/mKIp1Oe.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Cauliflower', 'Cauliflower description', 2.10, 'vegetable', 'https://i.imgur.com/9fWRXpu.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Garlic', 'Garlic description', 3.36, 'vegetable', 'https://i.imgur.com/fIls6jS.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Banana', 'Banana description', 5.25, 'vegetable', 'https://i.imgur.com/Nb1jaVS.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Beet', 'Beet description', 2.94, 'vegetable', 'https://i.imgur.com/OF6KBrh.jpg')
INSERT INTO hortifruti(name, description, price, category, image) VALUES('Cherry', 'Cherry description', 42, 'vegetable', 'https://i.imgur.com/xQ67Bv3.jpg')